/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otelrezervasyon;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static otelrezervasyon.dbConnection.con;

/**
 *
 * @author delilog
 */
public class musteriIslemleri extends javax.swing.JPanel {

    private final tableModel t;
    private String sql;
    private final DefaultTableModel tb;
    private final dbConnection db;
    private Vector veri;
    String ilkTelefon;
    int musteriID;
    /**
     * Creates new form musteriIslemleri
     */
    public musteriIslemleri() {
        initComponents();
        db = new dbConnection();
        t = new tableModel();
        sql = " Select ad,soyad,cinsiyet,tc,telefon,email,oda_no,on_odeme_tutar,toplam_oda_ucret,baslangic_tarihi,bitis_tarihi,"
                + "konak_sayisi from musteri,musteri_otel_bilgileri Where musteri.musteri_id=musteri_otel_bilgileri.musteri_id";
        
        tb = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int col) {
                if (col == 0) {
                    return false;
                }
                return true;
            }
        };
        
        t.tabloyuOlustur(sql, veri, tb);
        musteriTablo.setModel(tb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        odaNo = new javax.swing.JTextField();
        tarihIlk = new javax.swing.JTextField();
        tarihIki = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        musteriTablo = new javax.swing.JTable();
        musteriAd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        musteriSoyad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        musteriTelefon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        musteriMail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        guncelle = new javax.swing.JButton();
        onOdeme = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 445));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Arama"))));

        jLabel2.setText("İlk Tarih");

        jLabel3.setText("İkinci Tarih");

        jLabel4.setText("Oda No");

        tarihIlk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihIlkActionPerformed(evt);
            }
        });

        tarihIki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihIkiActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Müşteri", "Rezervasyon" }));

        jLabel1.setText("Tip");

        jButton2.setText("Arama");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tarihIlk, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tarihIki, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(odaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarihIlk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarihIki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Müşteri Listesi"));
        jPanel2.setPreferredSize(new java.awt.Dimension(674, 416));

        musteriTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musteriTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(musteriTablo);

        jLabel5.setText("Ad");

        jLabel6.setText("Soyad");

        jLabel7.setText("E-mail");

        musteriMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriMailActionPerformed(evt);
            }
        });

        jLabel8.setText("Telefon");

        guncelle.setText("Güncelle");
        guncelle.setEnabled(false);
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        jLabel9.setText("Ön Ödeme");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(musteriAd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(musteriSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musteriMail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(musteriTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(onOdeme, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guncelle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(82, 82, 82)
                .addComponent(jLabel6)
                .addGap(87, 87, 87)
                .addComponent(jLabel7)
                .addGap(77, 77, 77)
                .addComponent(jLabel8)
                .addGap(78, 78, 78)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musteriAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle)
                    .addComponent(onOdeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Diğer"));

        jButton1.setText("Yeni Müşteri Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Güncelle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tarihIlkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihIlkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihIlkActionPerformed

    private void tarihIkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihIkiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihIkiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
    musteriEkle frame = new musteriEkle();
    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    frame.pack();
    frame.setAlwaysOnTop(true);
    frame.setLocationRelativeTo(null);
    frame.addWindowListener(new java.awt.event.WindowAdapter() { 
        @Override 
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {

            t.tabloyuOlustur(sql, veri, tb);
            musteriTablo.setModel(tb);

        }
    
    }); 
    frame.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");  
      boolean tarihVar = false;
      int seciliIndex=jComboBox1.getSelectedIndex();
      if(seciliIndex==0){
             sql = " SELECT ad,soyad,cinsiyet,tc,telefon,email,oda_no,on_odeme_tutar,toplam_oda_ucret,baslangic_tarihi,bitis_tarihi,"
                + "konak_sayisi FROM musteri,musteri_otel_bilgileri WHERE musteri.musteri_id=musteri_otel_bilgileri.musteri_id";
        
      }
        
      else{
           sql = " SELECT ad,soyad,cinsiyet,tc,telefon,email,oda_no,odeme_tutari,toplam_oda_ucret,baslangic_tarihi,bitis_tarihi"
                   + " FROM rezervasyon";
        
      }
       
      if(!tarihIki.getText().equals("") && !tarihIlk.getText().equals("")){
          tarihVar=true;
          java.sql.Date sqldate2=null,sqldate=null;
           try {
               Date date;
               date = formatter.parse(tarihIlk.getText());
                sqldate = new java.sql.Date(date.getTime());
            
               Date date2 = formatter.parse(tarihIki.getText());
               sqldate2 = new java.sql.Date(date2.getTime());
               
           } catch (ParseException ex) {
               Logger.getLogger(musteriIslemleri.class.getName()).log(Level.SEVERE, null, ex);
           }
            
           
          if(seciliIndex==0){
          sql=sql+" AND (baslangic_tarihi>='"+sqldate+"' AND bitis_tarihi<='"+sqldate2+"')";
          }
          else{
          sql=sql+" WHERE baslangic_tarihi>='"+sqldate+"' AND bitis_tarihi<='"+sqldate2+"'";
 
          }
               
      }
      
      String odaNosu=odaNo.getText();
      
      if(!odaNosu.equals("")){
         
         if(seciliIndex==0){
          sql=sql+" AND (musteri_otel_bilgileri.oda_no="+odaNosu+")";
          }
         else{
                if(tarihVar){
                    
                   sql=sql+" AND (rezervasyon.oda_no="+odaNosu+")";
                   
                }
                else{
                    
                    sql=sql+" where rezervasyon.oda_no="+odaNosu;
                }
          }
          
          
      }
      
      
        t.tabloyuOlustur(sql, veri, tb);
        musteriTablo.setModel(tb);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void musteriTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriTabloMouseClicked
       
        
        try {
            db.dbBaglan();
            String sql2=" SELECT musteri.musteri_id,ad,soyad,cinsiyet,tc,telefon,email,oda_no,on_odeme_tutar,baslangic_tarihi,bitis_tarihi,"
                    + "konak_sayisi FROM musteri,musteri_otel_bilgileri WHERE musteri.musteri_id=musteri_otel_bilgileri.musteri_id";
            PreparedStatement ps = con.prepareStatement(sql2, ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            ps.executeQuery();
            
           
            ps.getResultSet().absolute(musteriTablo.getSelectedRow()+1);
             ilkTelefon=ps.getResultSet().getString("TELEFON");
            musteriAd.setText(ps.getResultSet().getString("AD"));
            musteriSoyad.setText(ps.getResultSet().getString("SOYAD"));
            musteriMail.setText(ps.getResultSet().getString("EMAIL"));
            musteriTelefon.setText(ps.getResultSet().getString("TELEFON"));
            onOdeme.setText(ps.getResultSet().getString("on_odeme_tutar"));
            musteriID=ps.getResultSet().getInt("Musteri_id");
            
            guncelle.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(musteriIslemleri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_musteriTabloMouseClicked

    private void musteriMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musteriMailActionPerformed

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        // TODO add your handling code here:
        
        String musteriAdText=musteriAd.getText();
        String musteriSoyadText=musteriSoyad.getText();
        String emailText=musteriMail.getText();
        String onOdemeText=onOdeme.getText();
        String musteriTel=musteriTelefon.getText();
        
        
        boolean ad,soyad,telefon,email,onOdemeK;
        
        textKontrolleri kontrol=new textKontrolleri();
        
        Color gri=new Color(237,237,237);
        Color kirmizi=new Color(215,134,130);
        
        if(kontrol.adSoyadKontrol(musteriAdText, "aaa")){
             musteriAd.setBackground(gri);
             ad=true;
        }
        else{
            musteriAd.setBackground(kirmizi);
            ad=false;
        }
        
        if(kontrol.adSoyadKontrol(musteriSoyadText, "aaa")){
             musteriSoyad.setBackground(gri);
             soyad=true;
        }
        else{
            musteriSoyad.setBackground(kirmizi);
            soyad=false;
        }
        
        
        if(kontrol.emailKontrol(emailText)){
         musteriMail.setBackground(gri);
         email=true;
        }
        else{
            musteriMail.setBackground(kirmizi);
            email=false;
        }
        
        
        if(kontrol.onOdemeKontrol(onOdemeText)){
         onOdeme.setBackground(gri);
         onOdemeK=true;
        } 
        else{
            onOdeme.setBackground(kirmizi);
            onOdemeK=false;
        }
        
        
        if(!ilkTelefon.equals(musteriTel)){
                if(kontrol.telefonKontrol(musteriTel)){
                 musteriTelefon.setBackground(gri);
                 telefon=true;
                }
        
                else{
                    musteriTelefon.setBackground(kirmizi);
                    telefon=false;
                }
          }
        else{
         musteriTelefon.setBackground(gri);
         telefon=true;
        }
        
        
        if(ad && soyad && telefon && email && onOdemeK){
            try {
                PreparedStatement ps;
                
                String sql2="UPDATE  musteri SET ad='"+musteriAdText+"', soyad='"+musteriSoyadText+
                "', telefon WHERE musteri_id="+musteriID;
                
                ps =dbConnection.getCon().prepareStatement(sql2);
               
                ps.execute();
            } catch (SQLException ex) {
                Logger.getLogger(musteriIslemleri.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
    }//GEN-LAST:event_guncelleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guncelle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField musteriAd;
    private javax.swing.JTextField musteriMail;
    private javax.swing.JTextField musteriSoyad;
    private javax.swing.JTable musteriTablo;
    private javax.swing.JTextField musteriTelefon;
    private javax.swing.JTextField odaNo;
    private javax.swing.JTextField onOdeme;
    private javax.swing.JTextField tarihIki;
    private javax.swing.JTextField tarihIlk;
    // End of variables declaration//GEN-END:variables
}
